export const DUMMY="DUMMY";
export const ALL_GENRES="ALL_GENRES";
export const ADD_GENRE="ADD_GENRE";
export const SHOW_VIDEOGAMES_PAGE="SHOW_VIDEOGAMES_PAGE";
export const DETAIL_VIDEOGAME="DETAIL_VIDEOGAME";
export const FILTER_TYPE_GENRES="genero";
export const FILTER_TYPE_DBOAPI="dbOapi";
export const ORDER_ALFABETICO="alfabetico";
export const ORDER_RATING="rating";
export const CHANGE_FILTER="CHANGE_FILTER";
export const CHANGE_FILTER_GENRE="CHANGE_FILTER_GENRE";
export const CHANGE_FILTER_DBOAPI="CHANGE_FILTER_DBOAPI";
export const CHANGE_ORDER="CHANGE_ORDER";
export const CHANGE_FILT_ORD="CHANGE_FILT_ORD";
export const NEW_PAGE="NEW_PAGE";
export const NEW_SEARCH="NEW_SEARCH";
export const ADDED_ID="ADDED_ID";
export const NEXT_PAGE="NEXT_PAGE";
export const LAST_PAGE="LAST_PAGE";
export const NUMBER_404="NUMBER_404"; //no exito en traer
export const NUMBER_200="NUMBER_200"; //exito en traer
export const NUMBER_000="NUMBER_000"; //buscando
export const SET_SEARCHING_000="SET_SEARCHING_000";
export const SEARCHING_DETAILED="SEARCHING_DETAILED";
export const FILTER_RATINGS_MENOR="FILTER_RATINGS_MENOR";
export const SOLO_AS="SOLO_AS";